repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
    -   id: check-manifest
        args: [--no-build-isolation]
        additional_dependencies: [oldest-supported-numpy, pkgconfig, Cython]

ci:
    autoupdate_schedule: monthly
